# Documentation:  http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
#matrix:
#  allow_failures:
#- julia_version: latest
# Work around a Travis bug
git:
  depth: 999999
notifications:
  email: false
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("RollingFunctions")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
