desc = "Roll a window over data, applying a function over the window."
keywords = ["rolling", "running", "windowed", "timeseries"]
name = "RollingFunctions"
uuid = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
repo = "https://github.com/JeffreySarnoff/RollingFunctions.jl.git"
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v0.7.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
Julia = ">= v1.0"
StatsBase = ">= v0.27.0"
